language: r
cache: packages
pandoc_version: 1.19.2.1

r_packages:
  - devtools

r_github_packages:
  - moderndive/moderndive
  - tidymodels/infer

before_script:
  - chmod +x ./_build.sh
#  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
#  - ./_deploy.sh

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep-history: true
  github_token: $TRAVISCI
  repo: Hendrik147/HR_Analytics_in_R_book
  # For testing purposes only
#  target_branch: deploy-from-travis
  # Switch back to gh-pages after getting the build to work
  # to deploy bookdown webpages
  target_branch: gh-pages
